services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "9071:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shopping_db

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.paymentserver
    container_name: payment-service
    ports:
      - "9061:9061"
    environment:
      - PORT_PAYMENT=9061
      - MONGO_URI=mongodb://mongodb:27017
      - PAYMENT_DB_NAME=payment_db
    depends_on:
      - mongodb

  shopping-service:
    build:
      context: .
      dockerfile: Dockerfile.httpserver
    container_name: shopping-service
    ports:
      - "9051:9051"
    environment:
      - PORT_SHOPPING=9051
      - MONGO_URI=mongodb://mongodb:27017
      - SHOPPING_DB_NAME=shopping_db
      - PAYMENT_SERVICE_BASE_URI=http://payment-service:9061
    depends_on:
      - mongodb
      - payment-service

volumes:
  mongodb_data:
